# 存储配置
store:
  engine: pebble
  path: ./slave1/db/

# server 相关
server:
  # grpc 配置
  grpc_port: 10001
  # http 配置
  http_port: 11001
  # 限流容量，每秒的 qps 限制
  rate: 30000

# 集群相关
cluster:
  path: ./slave1/raft/
  node_id: 2
  address: 127.0.0.1:12001
  master: 127.0.0.1:11000
  timeout: 10000
  join: false