global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: sdb
    static_configs:
      - targets: [ 'host.docker.internal:11000' ]
        labels:
          instance: host.docker.internal